---
- name: Populate service facts
  service_facts:
- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes
  when: ("'mysql'in services and ansible_facts.services['mysql.service'].status == 'disabled'") or ("'mariadb'in services and ansible_facts.services['mariadb.service'].status == 'disabled'")
- name: Create User
  mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_password}}"
    priv: "database.*:ALL"
    host: "%"
    state: present
  no_log: true
  when: ("'mysql'in services and ansible_facts.services['mysql.service'].status == 'enabled'") or ("'mariadb'in services and ansible_facts.services['mariadb.service'].status == 'enabled'")
- name: Create DB
  mysql_db:
    name: "{{database_name}}"
    state: present
  when: ("'mysql'in services and ansible_facts.services['mysql.service'].status == 'enabled'") or ("'mariadb'in services and ansible_facts.services['mariadb.service'].status == 'enabled'")
