---
- name: Install Security Certs
  package:
    name:
      - lsb-release
      - ca-certificates
      - apt-transport-https
      - software-properties-common
    state: present
- name: Check if sury repo is already installed
  stat:
    path: /etc/apt/sources.list.d/ondrej-ubuntu-php-jammy.list
  register: sury
- name: Install Sury Repo
  command: add-apt-repository ppa:ondrej/php -y
  when: ansible_distribution == 'Ubuntu' and sury.stat.exists == False
- name: install php and extensions
  package:
    update_cache: true
    name:
      - php8.1
      - php8.1-bcmath
      - php-common
      - php8.1-curl
      - libapache2-mod-php8.1
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-gd
      - php8.1-xml
      - php8.1-tokenizer
      - php8.1-zip
    state: latest
